/**
 * @file 002.cpp
 * @author Jianle
 * @brief Even Fibonacci numbers
 *        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
 *        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * @version 0.1
 * @date 2022-02-26
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#include <stdio.h>
#define s(x) (x)*(x)

int main(void)
{
    int a=5;
    int b;
    // a++;
    b=s(b=a++);
    printf("%d\n",b);
    
    return 0;
}